services:
  - type: web
    name: pimp-my-case-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11
    healthCheckPath: /health
    autoDeploy: true 