services:
  - type: web
    name: pimp-my-case-api
    runtime: python3
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api_server:app --host 0.0.0.0 --port $PORT
    plan: free
    env:
      - key: PYTHON_VERSION
        value: 3.11.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # This will need to be set manually in Render dashboard 